### ISSUE TITLE
spinner hangs endlessly in prepareRoom

### ISSUE THREAD

**Issue by cheluskin** [cloudflare/orange#128]
createMeeting doesn't seem to be called anywhere and therefore the spinner hangs endlessly in prepareRoom

**Comment by third774** [comment]
It's called here https://github.com/cloudflare/orange/blob/main/app/durableObjects/ChatRoom.server.ts#L108, and I can't seem to reproduce the issue — can you share more information?

- What commit are you on?
- Are you seeing this locally only or also in a deployed instance?
- How did you arrive at this conclusion?

**Comment by cheluskin** [comment]
My mistake, I apologize.
