### ISSUE TITLE
Allow customisation via variables

### ISSUE THREAD

**Issue by BenjaminEHowe** [cloudflare/orange#32]
While I appreciate that this application is primarily designed as a demonstration of what can be built using [Cloudflare Calls](https://developers.cloudflare.com/calls/), I think there's some merit in deploying an instance of the application largely as-is (after all, a number of businesses are spending non-trivial sums on licensing for e.g. Zoom).

To support this I think it makes sense to allow for customisation of various aspect of the application using variables -- for example, being able to change "Orange Meets" to "ACME Video Conferencing". What do y'all think? Happy to submit a pull request or two but wanted to engage in discussion here first.

**Comment by rcccf** [comment]
https://github.com/cloudflare/orange/fork 🙂

Let's keep this as a demo like what we intended to be, since we are also using it internally to catch early bugs with Calls.

**Comment by renandincer** [comment]
Yes! Please feel free to fork and make branding customizations you need for now :)
