### ISSUE TITLE
Allow Listener only

### ISSUE THREAD

**Issue by Wallacy** [cloudflare/orange#33]
One of my user case needs a headless listener to record the session. The Docs also shows that as option. But the API only exposes the /apps/{appId}/sessions/{sessionId}/tracks/new to join on existing session.

On a CEF environment i dont have any tracks do send.

**Comment by third774** [comment]
Are you able to add an inactive audio track like we're doing here?
https://github.com/cloudflare/orange/blob/main/app/utils/Peer.client.ts#L180

**Comment by Wallacy** [comment]
Yes, that should work. Thanks.
