### ISSUE TITLE
Microphone and Camera not working when deploy on cloudflare.

### ISSUE THREAD

**Issue by masnat** [cloudflare/orange#43]
I successfully deploy this project in https://orange.mala-widiyanto.workers.dev
I try allow mic and camera but there is no voice or camera from the joined users. 
am I missed a important step?

**Comment by third774** [comment]
@masnat — I just tried your link and it appears to work. Are you able to reproduce the issue on our demo deployment here?
https://demo.orange.cloudflare.dev/

Another helpful debugging question — what operating system and browser are you using? Were you prompted for webcam/mic access? If you dig into your browser settings for the page, can you see what the current webcam/mic permissions are? For example, on Chrome if you click the little settings toggle in the address bar you can see I have permission granted here
<img width="530" alt="image" src="https://github.com/cloudflare/orange/assets/8732191/0db63f4d-4f41-4780-9826-3558669cac44">

**Comment by masnat** [comment]
Hi @third774, according to the demo link, it's working fine. But when I deploy directly from the github. The problem is when 2 users join in the room the voice and the camera not working. 
The error show the websocket failed to connect.
![image](https://github.com/cloudflare/orange/assets/25217060/17558276-1ec1-4416-b7e2-74df468ea812)

**Comment by third774** [comment]
`localhost` implies this is running locally on your machine, and it is expected that other users cannot connect to your development server unless you explicitly configure it to allow incoming connections.

**Comment by masnat** [comment]
hi @third774, thank you for the information.
When I try to manually change the socket address, the mic and camera works.
But I don't know why my socket still pointing to the localhost after deploy to the cloudflare workers eventhough the host is window.location.host.
![image](https://github.com/cloudflare/orange/assets/25217060/1e3aebe4-5c6d-419d-9eab-702d652129ed)

I will close this issue.
